# Generated by Django 5.0.3 on 2024-03-15 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eid', models.IntegerField()),
                ('ename', models.CharField(max_length=20)),
                ('esal', models.IntegerField()),
                ('mode', models.CharField(choices=[('WFH', 'Work From Home'), ('WFO', 'Work From Office')], max_length=10)),
            ],
        ),
    ]
